version: '3.8'

services:
  # Service Backend (Express.js)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-1
    ports:
      - "4002:3310"
    environment:
      - PORT=3310
    volumes:
      - ./server:/app
      - /app/node_modules
      - csv_cache_volume:/app/CSVCache
    env_file:
      - ./server/.env.backend.local
    depends_on:
      - postgres_db
      - redis_cache
    restart: unless-stopped

  # Service Frontend (React/Vite)
  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "4001:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://backend:3310
      VITE_PUBLIC_API_URL: http://localhost:4002
    depends_on:
      - backend
    restart: unless-stopped

  postgres_db:
    image: postgis/postgis:17-3.4-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis_cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  csv_cache_volume:
    driver: local
